### ISSUE TITLE
Use of `highlighted_chunk_count` inside scoring function

### ISSUE THREAD

**Issue by crcheng** [brandonstarxel/chunking_evaluation#2] opened 2024-09-25 06:22 UTC
Hi, thanks for the useful benchmarking work! I'm looking to incorporate the context recall/precision metrics for my RAG system.

I just have a question regarding the use of `highlighted_chunk_count` inside the scoring function `_scores_from_dataset_and_retrievals`

- If the initial retrieval K is set to `-1`, the count for highlighted chunks are maintained [here](https://github.com/brandonstarxel/chunking_evaluation/blob/main/chunking_evaluation/evaluation_framework/base_evaluation.py#L397-L401).
- These counts are then used to filter the retrieved chunks metadata [here](https://github.com/brandonstarxel/chunking_evaluation/blob/main/chunking_evaluation/evaluation_framework/base_evaluation.py#L226) and [here](https://github.com/brandonstarxel/chunking_evaluation/blob/main/chunking_evaluation/evaluation_framework/base_evaluation.py#L258) 

I believe this means that the script will prematurely trim the list of retrieved chunks, so only the top N of K retrieved chunks are calculated for the scores. Is this the correct functionality based on the formula for IoU? My understanding is that we should still go thru the entire list of retrieve chunk metadata (so we shouldn't filter the list).

Thanks for the support!

**Comment by brandonstarxel** [comment] 2024-09-26 12:55
You have a keen eye and correctly understood our code! 
This is a somewhat technical detail over an arbitrary decision. We retrieve K chunks, but what value should K be? This is arbitrary. The bigger we make K, the more chunks will be returned and thus the IoU will drop. We know there's a fixed amount of 'useful' information (called 'excerpts' in the whitepaper) while lots of irrelevant info (all remaining chunks).

So ideally K isn't too large else IoU will be close to 0 even for perfect chunking methods. This is why we set it to 5.

The -1 special effect is from another thought we had. Suppose a chunker perfectly make two chunks both containing only useful information. If we aggressively set K=1, then the IoU would be low because it would have to miss one of the chunks (since it can only retrieve 1 of the two). Consequently, our metric gave a low score to a perfect chunking method (that's bad). So -1 makes it so K = the number of chunks which contain useful info (since we can calculate that ourself). And in this case would get back both chunks giving an IoU of 1.

**Comment by brandonstarxel** [comment] 2024-09-27 14:18
Yes, that is how it is meant to work when `retrieve = -1`. You are correct that a chunker may return those chunks later in the set and thus get trimmed out however that was by design. Afterall, you could return all chunks and say you have a perfect chunker. Of course, that's why other metrics exist that account for position in retrieval.

Regardless, you have the correct idea.

Since this is somewhat bizarre we use `retrieve = 5` in our white-paper since that's better understood by most readers. By default the evaluator uses that too. 

I believe you've got the idea so I shall close this issue. If you'd like to discuss it further, connect with me on [LinkedIn](https://www.linkedin.com/in/brandon-abreu-smith/) with a note saying you're from the github repo.

**Closed by brandonstarxel** 2024-09-27 14:18 UTC
